import threading
import subprocess

def run_script(script_name,argument):
   subprocess.run(["python3", script_name,str(argument)])

p381_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",381))
p382_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",382))
p384_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",384))
p385_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",385))
p388_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",388))
p389_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",389))
p390_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",390))
p408_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",408))
p409_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",409))
p410_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",410))
p411_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",411))
p414_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",414))
p417_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",417))
p418_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",418))
p419_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",419))
p422_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",422))
p433_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",433))
p439_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",439))
p440_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",440))
p442_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",442))
p443_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",443))
p445_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",445))
p454_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",454))
p455_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",455))

p381_thread.start()
p382_thread.start()
p384_thread.start()
p385_thread.start()
p388_thread.start()
p389_thread.start()
p390_thread.start()
p408_thread.start()
p409_thread.start()
p410_thread.start()
p411_thread.start()
p414_thread.start()
p417_thread.start()
p418_thread.start()
p419_thread.start()
p422_thread.start()
p433_thread.start()
p439_thread.start()
p440_thread.start()
p442_thread.start()
p443_thread.start()
p445_thread.start()
p454_thread.start()
p455_thread.start()

p381_thread.join()
p382_thread.join()
p384_thread.join()
p385_thread.join()
p388_thread.join()
p389_thread.join()
p390_thread.join()
p408_thread.join()
p409_thread.join()
p410_thread.join()
p411_thread.join()
p414_thread.join()
p417_thread.join()
p418_thread.join()
p419_thread.join()
p422_thread.join()
p433_thread.join()
p439_thread.join()
p440_thread.join()
p442_thread.join()
p443_thread.join()
p445_thread.join()
p454_thread.join()
p455_thread.join()

print("All the processes has been finished executing.")