import threading
import subprocess

def run_script(script_name,argument):
   subprocess.run(["python3", script_name,str(argument)])

p314_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",314))
p315_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",315))
p316_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",316))
p317_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",317))
p318_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",318))
p319_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",319))
p334_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",334))
p337_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",337))
p338_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",338))
p340_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",340))
p341_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",341))
p343_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",343))
p347_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",347))
p350_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",350))
p354_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",354))
p359_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",359))
p360_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",360))
p361_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",361))
p363_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",363))
p364_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",364))
p365_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",365))
p366_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",366))
p371_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",371))
p375_thread = threading.Thread(target=run_script, args=("Planck_elliptical_multiprocess.py",375))

p314_thread.start()
p315_thread.start()
p316_thread.start()
p317_thread.start()
p318_thread.start()
p319_thread.start()
p334_thread.start()
p337_thread.start()
p338_thread.start()
p340_thread.start()
p341_thread.start()
p343_thread.start()
p347_thread.start()
p350_thread.start()
p354_thread.start()
p359_thread.start()
p360_thread.start()
p361_thread.start()
p363_thread.start()
p364_thread.start()
p365_thread.start()
p366_thread.start()
p371_thread.start()
p375_thread.start()

p314_thread.join()
p315_thread.join()
p316_thread.join()
p317_thread.join()
p318_thread.join()
p319_thread.join()
p334_thread.join()
p337_thread.join()
p338_thread.join()
p340_thread.join()
p341_thread.join()
p343_thread.join()
p347_thread.join()
p350_thread.join()
p354_thread.join()
p359_thread.join()
p360_thread.join()
p361_thread.join()
p363_thread.join()
p364_thread.join()
p365_thread.join()
p366_thread.join()
p371_thread.join()
p375_thread.join()

print("All the processes has been finished executing.")